# https://www.home-assistant.io/integrations/default_config/
default_config:

# https://www.home-assistant.io/integrations/homeassistant/
homeassistant:
  debug: true

# https://www.home-assistant.io/integrations/logger/
logger:
  default: info
  logs:
    custom_components.multi_person_weight_sensor: debug

template:
  - sensor:
    - name: "Test input weight sensor"
      unit_of_measurement: kg
      state: 80
      state_class: measurement
      device_class: weight

